import LegalLean.Core
import LegalLean.Defeasible
import LegalLean.Solver
import LegalLean.IR.Legal
import LegalLean.CaseStudies.IRC163h
import LegalLean.CaseStudies.IRC163h.Theorems
import LegalLean.CaseStudies.O1Visa
import LegalLean.CaseStudies.TCPCode
import LegalLean.TypeclassConstraint
